stages:
  preprocessing:
    cmd: python src/preprocessing.py
    deps:
    - data/raw/Churn Prediction DataSet.csv
    - src/preprocessing.py
    outs:
    - data/processed/X_train.csv
    - data/processed/X_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv

  train:
    cmd: python3 src/train.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
    - src/train.py
    outs:
    - models
  evaluate:
    cmd: python3 src/evaluate.py
    deps:
    - data/processed/X_test.csv
    - data/processed/y_test.csv
    - models
    - src/evaluate.py
    outs:
    - evaluation
