stages:
  ingestion:
    cmd: python src/ingestion.py
    deps:
      - data/external/Churn Prediction DataSet.csv
      - src/ingestion.py
    outs:
      - data/raw

  validation:
    cmd: python src/validation.py
    deps:
      - data/raw/Churn Prediction DataSet.csv
      - src/validation.py
    outs: []

  preprocessing:
    cmd: python src/preprocessing.py
    deps:
      - data/raw/Churn Prediction DataSet.csv
      - src/preprocessing.py
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - src/train.py
    outs:
      - models

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - data/processed/X_test.csv
      - data/processed/y_test.csv
      - models
      - src/evaluate.py
    outs:
      - evaluation

  register:
    cmd: python src/register.py
    deps:
      - src/register.py
      - models
    outs: []

